name: flutter_color_palette
description: "A comprehensive color palette widget for Flutter applications."
version: 1.0.0
homepage: https://github.com/DarienRomero/flutter_color_palette

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

